# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:05:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ChapterSchema(BaseModel):
    chapter_number: Optional[int] = None
    chapter_summary: Optional[str] = None
    name: Optional[str] = None
    name_meaning: Optional[str] = None
    name_translation: Optional[str] = None
    name_transliterated: Optional[str] = None
    verses_count: Optional[int] = None


class VerseSchema(BaseModel):
    meaning: Optional[str] = None
    text: Optional[str] = None
    transliteration: Optional[str] = None
    verse_number: Optional[str] = None
    word_meanings: Optional[str] = None


class Language(Enum):
    hi = 'hi'


class ChapterNumber(Enum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class VerseNumber(Enum):
    field_1 = 1
    field_2 = 2
    field_3 = 3


class AuthOauthTokenPostRequest(BaseModel):
    client_id: str = Field(
        ..., description="Your app's client_id. Get from API dashboard."
    )
    client_secret: str = Field(
        ..., description="Your app's client_secret. Get from API dashboard."
    )
    grant_type: str = Field(..., description='Grant Type.')
    scope: str = Field(..., description='The resources that you would like to access.')
